aws_access_key_id = "AKIATESTACCESSKEY123"
fazfazfa
fazfazfa
fazfazfza port
adaaaaaaaaaaaaaaaaaafazfzfzfzaf
fafazfaz host 
azfzafazfzaffafaz
azfazfazfzafazfazf
zfazfazfa
fazfazfa
azfazfaz
fazfazfafaf
region = "us-east-1"
dazdaz
dazdazdaz
azddazdazd
azdzadazd
azdazdza
dazdaz
da
aws_secret_access_key = "superSecretKey1234567890+/="
dzadazdzadzadzaddzadaz
dzadazd
port = 587
dzadzadazdazd
dzazadza
dazdazdaz
dad
azd
azd
azd
azdazd
azzd
dzadza
host = "email-smtp.us-east-1.amazonaws.com"
dzadazdzadza
password = "SuperSecretPass456"
dzadazdza
user = "AKIATESTACCESSKEY123"
dzadazdadzaz
from = email@email.com
