AWS_ACCESS_KEY_ID=AKIATESTKEY123
AWS_SECRET_ACCESS_KEY=secret123456
AWS_REGION=us-east-1
EMAIL_HOST=email-smtp.us-east-1.amazonaws.com
EMAIL_PORT=587
EMAIL_USER=AKIATESTKEY123
EMAIL_PASS=secret123456


{
  "Identities": ["admin@site.com", "bot@site.com"]
}
