AWS_ACCESS_KEY_ID=AKIATESTKEY123
dzadzadazdza
dzadazdazdza
dzadazdazdza
azddazdaz
AWS_SECRET_ACCESS_KEY=secret123456
dzadazdaz
dzadazdzadz
azdadzadzaa
dadada
dada
AWS_REGION=us-east-1
d
da
da
da
d
ad
da
dzadzadzazda
EMAIL_HOST=email-smtp.us-east-1.amazonaws.com
dzadazdadzadza
EMAIL_PORT=587
dzadazdaz
EMAIL_USER=AKIATESTKEY123
eaddazdaz
EMAIL_PASS=secret123456
